export const visualizerData = [
  {
    Mon: [
      {
        timeSlot: "9am",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea10",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "9:00",
            EndTime: "10:15",
            marginTop: "-95px",
            marginLeft: "-55px",
            id: 1,
          },
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea2",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "9:15",
            EndTime: "11:30",
            marginTop: "-84px",
            marginLeft: "-10px",
            id: 2,
          },
        ],
      },
      {
        timeSlot: "1am",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea3",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:30",
            EndTime: "3:30",
            marginTop: "84px",
            marginLeft: "-71px",
            id: 3,
          },
        ],
      },
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea4",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "5:00",
            EndTime: "6:30",
            marginTop: "223px",
            marginLeft: "-71px",
            id: 4,
          },
        ],
      },
    ],
  },
  {
    tue: [
      {
        timeSlot: "10am",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea5",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "10:15",
            EndTime: "12:30",
            marginTop: "-47px",
            marginLeft: "22px",
            id: 5,
          },
        ],
      },
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea7",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "5:00",
            EndTime: "6:30",
            marginTop: "219px",
            marginLeft: "43px",
            id: 6,
          },
        ],
      },
    ],
  },
  {
    wed: [
      {
        timeSlot: "1pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea8",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:30",
            EndTime: "3:30",
            marginTop: "84px",
            marginLeft: "95px",
            id: 7,
          },
        ],
      },
      {
        timeSlot: "7pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea10",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "7:00",
            EndTime: "8:00",
            marginTop: "299px",
            marginLeft: "95px",
            id: 8,
          },
        ],
      },
    ],
  },
  {
    thru: [
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea11",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:00",
            EndTime: "3:30",
            marginTop: "63px",
            marginLeft: "162px",
            id: 9,
          },
        ],
      },
    ],
  },
  {
    Fri: [
      {
        timeSlot: "10am",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea12",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "10:30",
            EndTime: "11:30",
            marginTop: "-36px",
            marginLeft: "231px",
            id: 10,
          },
        ],
      },
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea14",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "5:00",
            EndTime: "6:30",
            marginTop: "219px",
            marginLeft: "199px",
            id: 11,
          },
        ],
      },
    ],
  },
];

export const visualizerElectiveData = [
  {
    Mon: [
      {
        timeSlot: "9am",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea15",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "9:00",
            EndTime: "10:15",
            marginTop: "-95px",
            marginLeft: "-55px",
          },
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea11",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "9:15",
            EndTime: "11:30",
            marginTop: "-84px",
            marginLeft: "-10px",
          },
        ],
      },
      {
        timeSlot: "1am",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea12",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:30",
            EndTime: "3:30",
            marginTop: "84px",
            marginLeft: "-71px",
          },
        ],
      },
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea15",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "5:00",
            EndTime: "6:30",
            marginTop: "223px",
            marginLeft: "-71px",
          },
        ],
      },
    ],
  },
  {
    tue: [
      {
        timeSlot: "10am",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea11",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "10:15",
            EndTime: "12:30",
            marginTop: "-47px",
            marginLeft: "22px",
          },
        ],
      },
      {
        timeSlot: "1pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea12",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:30",
            EndTime: "3:30",
            marginTop: "80px",
            marginLeft: "-6px",
          },
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea11",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:00",
            EndTime: "3:00",
            marginTop: "62px",
            marginLeft: "43px",
          },
        ],
      },
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea12",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "5:00",
            EndTime: "6:30",
            marginTop: "219px",
            marginLeft: "43px",
          },
        ],
      },
    ],
  },
  {
    wed: [
      {
        timeSlot: "1pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea15",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:30",
            EndTime: "3:30",
            marginTop: "84px",
            marginLeft: "95px",
          },
        ],
      },
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea12",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "5:00",
            EndTime: "6:30",
            marginTop: "220px",
            marginLeft: "95px",
          },
        ],
      },
      {
        timeSlot: "7pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea11",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "7:00",
            EndTime: "8:00",
            marginTop: "299px",
            marginLeft: "95px",
          },
        ],
      },
    ],
  },
  {
    thru: [
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea15",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:00",
            EndTime: "3:30",
            marginTop: "63px",
            marginLeft: "162px",
          },
        ],
      },
    ],
  },
  {
    Fri: [
      {
        timeSlot: "10am",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea11",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "10:30",
            EndTime: "11:30",
            marginTop: "-36px",
            marginLeft: "231px",
          },
        ],
      },
      {
        timeSlot: "1pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea12",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:30",
            EndTime: "3:00",
            marginTop: "80px",
            marginLeft: "150px",
          },
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea11",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "1:00",
            EndTime: "3:30",
            marginTop: "67px",
            marginLeft: "199px",
          },
        ],
      },
      {
        timeSlot: "5pm",
        events: [
          {
            Info: " FINANCE 385.01 ",
            color: "event CoreArea15",
            img: "/o/stanford-clce-theme/images/icons/fav_icon.svg",
            StartTime: "5:00",
            EndTime: "6:30",
            marginTop: "219px",
            marginLeft: "199px",
          },
        ],
      },
    ],
  },
];

export const SampleVisuilizerData = {
  quartersDropDown: ["Spring 2023-2024"],
  weekPatterns: ["week 1-5"],
  currentWeekTab: "week 1-5",
  weekMap: {
    MON: [
      {
        classId: 13158,
        classNumber: 31035,
        subjectCode: "OB",
        catalogNumberCode: "388",
        classSection: "01",
        title: "Leadership in the Entertainment Industry",
        instructorName: "B Guttentag",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["MON | 02:50 PM - 05:50 PM"],
        meetingDays: ["MON"],
        meetingDaysMap: {
          MON: ["02:50 PM - 05:50 PM"],
        },

        conflictedSections: null,
        preference: false,
        enrolled: true,
      },
      {
        classId: 13163,
        classNumber: 31037,
        subjectCode: "ALP",
        catalogNumberCode: "303",
        classSection: "01",
        title: "Analysis and Measurement of Impact",
        instructorName: "J Foroughi",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["MON, THU | 10:00 AM - 11:45 AM"],
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["10:00 AM - 11:45 AM"],
          THU: ["10:00 AM - 11:45 AM"],
        },
        conflictedSections: null,
        preference: true,
        enrolled: false,
      },
      {
        classId: 13052,
        classNumber: 1008,
        subjectCode: "FINANCE",
        catalogNumberCode: "350",
        classSection: "01",
        title: "Corporate Financial Modeling",
        instructorName: "P DeMarzo",
        academicYear: "2023-2024",
        conflictStatus: "PreferenceConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: [
          "MON | 06:30 PM - 07:50 PM",
          "THU | 04:25 PM - 06:10 PM",
        ],
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["06:30 PM - 07:50 PM"],
          THU: ["04:25 PM - 06:10 PM"],
        },
        conflictedSections: ["GSBGEN 352.02", "OB 374.02"],
        preference: true,
        enrolled: false,
      },
      {
        classId: 13086,
        classNumber: 1064,
        subjectCode: "OB",
        catalogNumberCode: "374",
        classSection: "02",
        title: "Interpersonal Dynamics",
        instructorName: "A Corney",
        academicYear: "2023-2024",
        conflictStatus: "Conflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: [
          "MON, THU | 04:25 PM - 06:10 PM",
          "MON | 07:00 PM - 10:00 PM",
        ],
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["04:25 PM - 06:10 PM", "07:00 PM - 10:00 PM"],
          THU: ["04:25 PM - 06:10 PM"],
        },
        conflictedSections: ["FINANCE 350.01", "OB 388.01"],
        preference: true,
        enrolled: false,
      },
    ],
    TUE: [
      {
        classId: 13486,
        classNumber: 33358,
        subjectCode: "STRAMGT",
        catalogNumberCode: "329",
        classSection: "01",
        title: "The Grand Bazaar on Clouds: Strategy for Marketplaces",
        instructorName: "M Akbarpour",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["TUE, FRI | 01:15 PM - 02:35 PM"],
        meetingDays: ["TUE", "FRI"],
        meetingDaysMap: {
          TUE: ["01:15 PM - 02:35 PM"],
          FRI: ["01:15 PM - 02:35 PM"],
        },
        conflictedSections: null,
        preference: false,
        enrolled: true,
      },
      {
        classId: 13403,
        classNumber: 32683,
        subjectCode: "MGTECON",
        catalogNumberCode: "300",
        classSection: "06",
        title: "Growth and Stabilization in the Global Economy",
        instructorName: "S Di Tella",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["TUE, FRI | 02:50 PM - 04:10 PM"],
        meetingDays: ["TUE", "FRI"],
        meetingDaysMap: {
          TUE: ["02:50 PM - 04:10 PM"],
          FRI: ["02:50 PM - 04:10 PM"],
        },
        conflictedSections: null,
        preference: false,
        enrolled: true,
      },
      {
        classId: 13167,
        classNumber: 31052,
        subjectCode: "GSBGEN",
        catalogNumberCode: "514",
        classSection: "01",
        title:
          "Creating and Scaling High Potential Ventures in Developing Economies (Cases)",
        instructorName: "S Ciesinski",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["TUE | 10:00 AM - 11:45 AM"],
        meetingDays: ["TUE"],
        meetingDaysMap: {
          TUE: ["10:00 AM - 11:45 AM"],
        },
        conflictedSections: null,
        preference: false,
        enrolled: true,
      },
      {
        classId: 13168,
        classNumber: 31051,
        subjectCode: "GSBGEN",
        catalogNumberCode: "339",
        classSection: "01",
        title: "Negotiation Dynamics in Sports, Entertainment and Media",
        instructorName: "G Foster",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["TUE, FRI | 08:00 AM - 09:45 AM"],
        meetingDays: ["TUE", "FRI"],
        meetingDaysMap: {
          TUE: ["08:00 AM - 09:45 AM"],
          FRI: ["08:00 AM - 09:45 AM"],
        },
        conflictedSections: null,
        preference: true,
        enrolled: false,
      },
    ],
    WED: [],
    THU: [
      {
        classId: 13163,
        classNumber: 31037,
        subjectCode: "ALP",
        catalogNumberCode: "303",
        classSection: "01",
        title: "Analysis and Measurement of Impact",
        instructorName: "J Foroughi",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["MON, THU | 10:00 AM - 11:45 AM"],
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["10:00 AM - 11:45 AM"],
          THU: ["10:00 AM - 11:45 AM"],
        },
        conflictedSections: null,
        preference: true,
        enrolled: false,
      },
      {
        classId: 13052,
        classNumber: 1008,
        subjectCode: "FINANCE",
        catalogNumberCode: "350",
        classSection: "01",
        title: "Corporate Financial Modeling",
        instructorName: "P DeMarzo",
        academicYear: "2023-2024",
        conflictStatus: "PreferenceConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: [
          "MON | 06:30 PM - 07:50 PM",
          "THU | 04:25 PM - 06:10 PM",
        ],
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["06:30 PM - 07:50 PM"],
          THU: ["04:25 PM - 06:10 PM"],
        },
        conflictedSections: ["OB 374.01", "OB 374.02"],
        preference: true,
        enrolled: false,
      },
      {
        classId: 13086,
        classNumber: 1063,
        subjectCode: "OB",
        catalogNumberCode: "374",
        classSection: "01",
        title: "Interpersonal Dynamics",
        instructorName: "H Most",
        academicYear: "2023-2024",
        conflictStatus: "PreferenceConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: [
          "THU | 02:50 PM - 05:50 PM",
          "THU | 07:00 PM - 10:00 PM",
        ],
        meetingDays: ["THU"],
        meetingDaysMap: {
          THU: ["02:50 PM - 05:50 PM", "07:00 PM - 10:00 PM"],
        },
        conflictedSections: ["FINANCE 350.01", "FINANCE 350.02"],
        preference: true,
        enrolled: false,
      },
      {
        classId: 13043,
        classNumber: 1002,
        subjectCode: "GSBGEN",
        catalogNumberCode: "352",
        classSection: "01",
        title: "Winning Writing",
        instructorName: "G Kramon",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["THU | 08:15 AM - 11:15 AM"],
        meetingDays: ["THU"],
        meetingDaysMap: {
          THU: ["08:15 AM - 11:15 AM"],
        },
        conflictedSections: null,
        preference: true,
        enrolled: false,
      },
      {
        classId: 13052,
        classNumber: 1009,
        subjectCode: "FINANCE",
        catalogNumberCode: "350",
        classSection: "02",
        title: "Corporate Financial Modeling",
        instructorName: "P DeMarzo",
        academicYear: "2023-2024",
        conflictStatus: "PreferenceConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: [
          "MON | 06:30 PM - 07:50 PM",
          "THU | 06:30 PM - 08:15 PM",
        ],
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["06:30 PM - 07:50 PM"],
          THU: ["06:30 PM - 08:15 PM"],
        },
        conflictedSections: ["OB 374.01", "OB 374.02"],
        preference: true,
        enrolled: false,
      },
      {
        classId: 13086,
        classNumber: 1064,
        subjectCode: "OB",
        catalogNumberCode: "374",
        classSection: "02",
        title: "Interpersonal Dynamics",
        instructorName: "A Corney",
        academicYear: "2023-2024",
        conflictStatus: "Conflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: [
          "MON, THU | 04:25 PM - 06:10 PM",
          "MON | 07:00 PM - 10:00 PM",
        ],
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["04:25 PM - 06:10 PM", "07:00 PM - 10:00 PM"],
          THU: ["04:25 PM - 06:10 PM"],
        },
        conflictedSections: [
          "FINANCE 350.01",
          "FINANCE 350.02",
          "OB 388.01",
          "OB 502.01",
        ],
        preference: true,
        enrolled: false,
      },
    ],
    FRI: [
      {
        classId: 13486,
        classNumber: 33358,
        subjectCode: "STRAMGT",
        catalogNumberCode: "329",
        classSection: "01",
        title: "The Grand Bazaar on Clouds: Strategy for Marketplaces",
        instructorName: "M Akbarpour",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["TUE, FRI | 01:15 PM - 02:35 PM"],
        meetingDays: ["TUE", "FRI"],
        meetingDaysMap: {
          TUE: ["01:15 PM - 02:35 PM"],
          FRI: ["01:15 PM - 02:35 PM"],
        },
        conflictedSections: null,
        preference: false,
        enrolled: true,
      },
      {
        classId: 13403,
        classNumber: 32683,
        subjectCode: "MGTECON",
        catalogNumberCode: "300",
        classSection: "06",
        title: "Growth and Stabilization in the Global Economy",
        instructorName: "S Di Tella",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["TUE, FRI | 02:50 PM - 04:10 PM"],
        meetingDays: ["TUE", "FRI"],
        meetingDaysMap: {
          TUE: ["02:50 PM - 04:10 PM"],
          FRI: ["02:50 PM - 04:10 PM"],
        },
        conflictedSections: null,
        preference: false,
        enrolled: true,
      },
      {
        classId: 13168,
        classNumber: 31051,
        subjectCode: "GSBGEN",
        catalogNumberCode: "339",
        classSection: "01",
        title: "Negotiation Dynamics in Sports, Entertainment and Media",
        instructorName: "G Foster",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        dateRange: ["Apr 04 - Jun 04"],
        meetingDayTimePatterns: ["TUE, FRI | 08:00 AM - 09:45 AM"],
        meetingDays: ["TUE", "FRI"],
        meetingDaysMap: {
          TUE: ["08:00 AM - 09:45 AM"],
          FRI: ["08:00 AM - 09:45 AM"],
        },
        conflictedSections: null,
        preference: true,
        enrolled: false,
      },
    ],
  },
  enablePreferenceColor: true,
  enableConflictColor: true,
  enableEnrollmentColor: true,
  enablePreferenceConflictColor: true,
  conflictedResponsesInfo: [
    {
      conflictStatus: "PreferenceConflict",
      conflictedCourses: ["GSBGEN 352.02", "OB 374.02"],
      classId: 13052,
      classNumber: 1008,
      subjectCode: "FINANCE",
      catalogNumberCode: "350",
      classSection: "01",
      title: "Corporate Financial Modeling",
      academicYear: "2023-2024",
      conflictedSectionsInfo: [
        {
          conflictSection: "FINANCE 350.02",
          conflictStatus: "Enrolled",
        },
        {
          conflictSection: "FINANCE 350.02",
          conflictStatus: "PreferenceConflict",
        },
      ],
    },
    {
      conflictStatus: "PreferenceConflict",
      conflictedCourses: ["FINANCE 350.01"],
      classId: 13043,
      classNumber: 1003,
      subjectCode: "GSBGEN",
      catalogNumberCode: "352",
      classSection: "02",
      title: "Winning Writing",
      academicYear: "2023-2024",
      conflictedSectionsInfo: [
        {
          conflictSection: "FINANCE 350.02",
          conflictStatus: "Enrolled",
        },
      ],
    },
    {
      conflictStatus: "Conflict",
      conflictedCourses: ["FINANCE 350.01", "OB 388.01"],
      classId: 13086,
      classNumber: 1064,
      subjectCode: "OB",
      catalogNumberCode: "374",
      classSection: "02",
      title: "Interpersonal Dynamics",
      academicYear: "2023-2024",
      conflictedSectionsInfo: [
        {
          conflictSection: "FINANCE 350.02",
          conflictStatus: "Enrolled",
        },
        {
          conflictSection: "FINANCE 350.02",
          conflictStatus: "PreferenceConflict",
        },
      ],
    },
  ],
};

export const scheduleData = {
  quartersDropDown: [
    "Spring 2023-2024",
    "winter 2023-2024",
    "summer 2022-2021",
  ],
  weekPatterns: [
    "week 1",
    "week 2- 4",
    "week 5",
    "week 6- 8",
    "week 9- 10",
    "week 9- 10",
    "week 9- 10",
    "week 9- 10",
    "week 9- 10",
    "week 9- 10",
  ],
  currentWeekTab: "week 1",
  weekMap: {
    MON: [
      {
        classId: 13060,
        classNumber: 1013,
        subjectCode: "STRAMGT",
        catalogNumberCode: "510",
        classSection: "01",
        title: "Conversations in Management",
        instructorName: "H Grousbeck",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "5",
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["08:00 AM - 9:45 AM"],
          THU: ["10:00 AM - 11:45 AM"],
        },
        dateRange: ["Apr 04 - Jun 04", "Apr 04 - Jun 04"],
        meetingDayTimePatterns: [
          "MON | 06:30 PM - 07:50 PM",
          "THU | 06:30 PM - 08:15 PM",
        ],
        conflictedSections: null,
        enrolled: true,
        preference: false,
      },
      {
        classId: 13052,
        classNumber: 1008,
        subjectCode: "FINANCE",
        catalogNumberCode: "350",
        classSection: "01",
        title: "Corporate Financial Modeling",
        instructorName: "P DeMarzo",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["06:30 PM - 07:50 PM"],
          THU: ["04:25 PM - 06:10 PM"],
        },
        conflictedSections: [],
        enrolled: false,
        preference: true,
      },
    ],
    TUE: [
      {
        classId: 13078,
        classNumber: 1053,
        subjectCode: "STRAMGT",
        catalogNumberCode: "353",
        classSection: "01",
        title: "Entrepreneurship: Formation of New Ventures",
        instructorName: "J Ellis",
        academicYear: "2023-2024",
        conflictStatus: "Conflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        meetingDays: ["TUE", "FRI"],
        meetingDaysMap: {
          TUE: ["10:00 AM - 11:45 AM"],
          FRI: ["10:00 AM - 11:45 AM"],
        },
        dateRange: ["Apr 04 - Jun 04", "Apr 04 - Jun 04"],
        meetingDayTimePatterns: [
          "MON | 06:30 PM - 07:50 PM",
          "THU | 06:30 PM - 08:15 PM",
        ],
        conflictedSections: ["STRAMGT 510.01", "STRAMGT 510.01"],
        enrolled: false,
        preference: true,
      },
    ],
    WED: [],
    THU: [
      {
        classId: 13060,
        classNumber: 1013,
        subjectCode: "STRAMGT",
        catalogNumberCode: "510",
        classSection: "01",
        title: "Conversations in Management",
        instructorName: "H Grousbeck",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "5",
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["10:00 AM - 11:45 AM"],
          THU: ["10:00 AM - 11:45 AM"],
        },
        conflictedSections: null,
        enrolled: true,
        preference: false,
      },
      {
        classId: 13052,
        classNumber: 1008,
        subjectCode: "FINANCE",
        catalogNumberCode: "350",
        classSection: "01",
        title: "Corporate Financial Modeling",
        instructorName: "P DeMarzo",
        academicYear: "2023-2024",
        conflictStatus: "NoConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        meetingDays: ["MON", "THU"],
        meetingDaysMap: {
          MON: ["06:30 PM - 07:50 PM"],
          THU: ["04:25 PM - 06:10 PM"],
        },
        conflictedSections: [],
        enrolled: false,
        preference: true,
      },
      {
        classId: 13053,
        classNumber: 1010,
        subjectCode: "STRAMGT",
        catalogNumberCode: "549",
        classSection: "01",
        title: "Search Fund Garage",
        instructorName: "P Kelly",
        academicYear: "2023-2024",
        conflictStatus: "PreferenceConflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        meetingDays: ["THU"],
        meetingDaysMap: {
          THU: ["10:00 AM - 11:45 AM"],
        },
        conflictedSections: ["STRAMGT 510.01"],
        enrolled: false,
        preference: true,
      },
    ],
    FRI: [
      {
        classId: 13078,
        classNumber: 1053,
        subjectCode: "STRAMGT",
        catalogNumberCode: "353",
        classSection: "01",
        title: "Entrepreneurship: Formation of New Ventures",
        instructorName: "J Ellis",
        academicYear: "2023-2024",
        conflictStatus: "Conflict",
        weekStartNumber: "1",
        weekEndNumber: "10",
        meetingDays: ["TUE", "FRI"],
        meetingDaysMap: {
          TUE: ["10:00 AM - 11:45 AM"],
          FRI: ["10:00 AM - 11:45 AM"],
        },
        conflictedSections: [],
        enrolled: true,
        preference: false,
      },
    ],
  },
  enablePreferenceColor: true,
  enableConflictColor: true,
  enableEnrollmentColor: true,
  enablePreferenceConflictColor: true,
  conflictedResponsesInfo: [
    {
      classId: 13053,
      classNumber: 1010,
      subjectCode: "STRAMGT",
      catalogNumberCode: "549",
      classSection: "01",
      title: "Search Fund Garage",
      academicYear: "2023-2024",
      conflictStatus: null,
      conflictedCourses: ["OIT 281.01"],
    },
  ],
};
